services:
  - type: web
    name: adil-exam
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_REGISTRATION_CODE
        sync: false
